# Generated by Django 4.0.5 on 2022-07-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_number_alter_task_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='message',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
