# Generated by Django 4.0.5 on 2022-07-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default='ffffff', max_length=6),
        ),
    ]
