# Generated by Django 4.0.5 on 2022-07-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_created_at_task_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='geometry',
            field=models.IntegerField(default=0),
        ),
    ]
