# Generated by Django 4.0.5 on 2022-07-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='number',
        ),
        migrations.AddField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
